[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
minttoken = "BmZuBzHwVSZWoDrBdepW3xR1BW6TBWcvMvWjrak3dWtp"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = 'C:\Users\Wiki\.config/solana/id.json'

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
